### ISSUE TITLE
Pols should be XX, XY, YX, YY

### ISSUE THREAD

**Issue by tremou** [cyriltasse/DynSpecMS#25]
Does it work only with linear feeds? 
I tried it on VLA -C band data and I get the following error. 

```
Traceback (most recent call last):
  File "/lustre/aoc/sciops/etremou/soft/DynSpecMS/splitcatalog_fixes/DynSpecMS/scripts/ms2dynspec.py", line 237, in <module>
    main(args)
  File "/lustre/aoc/sciops/etremou/soft/DynSpecMS/splitcatalog_fixes/DynSpecMS/scripts/ms2dynspec.py", line 150, in main
    D = ClassDynSpecMS(ListMSName=MSList, 
  File "/users/etremou/.local/lib/python3.9/site-packages/DynSpecMS-0.1.0-py3.9.egg/DynSpecMS/ClassDynSpecMS.py", line 148, in __init__
    self.ReadMSInfos()
  File "/users/etremou/.local/lib/python3.9/site-packages/DynSpecMS-0.1.0-py3.9.egg/DynSpecMS/ClassDynSpecMS.py", line 600, in ReadMSInfos
    raise ValueError("Pols should be XX, XY, YX, YY")
ValueError: Pols should be XX, XY, YX, YY
```

Thanks, 
Lilia

**Comment by o-smirnov** [comment]
@Talon Myburgh ***@***.***> has a meerkat version.

Cheers,
Oleg

--

**Comment by talonmyburgh** [comment]
@tremou have a try with my branch [SplitCatalog_fixes](https://github.com/cyriltasse/DynSpecMS/tree/SplitCatalog_fixes). I use that for MeerKAT datasets. Can also just pip install it normally (i.e. `pip install <path-to-cloned-folder>`).

**Comment by tremou** [comment]
thanks. I do use the SplitCatalog_fixes branch, and I run it without any issue in MeerKAT data since it's XX, YY , etc. the issue is present is with the RR, LL, etc at VLA data.

**Comment by talonmyburgh** [comment]
Ah I see... apologies, I did not read that correctly. Yes, you are correct it appears from the code that measurement set column `"CORR_TYPE"` must be [9,10,11,12] which correspond to "XX, XY, YX, YY". 
@cyriltasse might be able to comment further on what would be required to support other `"CORR_TYPE"`.

**Comment by cyriltasse** [comment]
I have this raise condition because the 4 lines here https://github.com/cyriltasse/DynSpecMS/blob/e3d828f6bb1e45cec5ffbe1bc3231fff02121285/DynSpecMS/ClassDynSpecMS.py#L1042, ie the mapping from cube slices to IQUV should be different for other corr types. It's quite simple to change but I'm in hollidays right now! @tremou you could add a `corr_type` attribute to the class and change the mapping and the raise condition accordingly? (if you do so, create a separate branch).
